src/gts_service/urls.py
from __future__ import annotations

from django.urls import path

from gts_service import views

urlpatterns = [
    path("", views.main),
]

src/gts_service/forms.py
from __future__ import annotations

from django import forms

forms.Widget()


class UploadForm(forms.Form):
    solderpaste_file = forms.FileField(
        label="Solder paste layer file, ends with '.gtp'"
    )
    outline_file = forms.FileField(
        label="Outline layer file, ends with '.gko' (Optional)",
        required=False,
        help_text="Outline of the board used to create the stencil. To create a stencil of different size, use the options below instead.",
    )
    stencil_thickness = forms.FloatField(
        label="Thickness (in mm) of the stencil. Make sure this is a multiple of the layer height you use for printing.",
        initial=0.2,
    )
    gap = forms.FloatField(
        label="Gap (in mm) around the board outline. Increase this if the fit of the stencil in the ledge/frame is too tight.",
        initial=0.0,
    )
    include_ledge = forms.BooleanField(
        label="Include a ledge around half the outline of the board, to allow aligning the stencil more easily.",
        initial=True,
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "collapse-checkbox include-ledge"}),
    )
    ledge_thickness = forms.FloatField(
        label="Thickness of the stencil ledge. This should be less than the thickness of the PCB.",
        initial=1.2,
    )
    increase_hole_size_by = forms.FloatField(
        label="Increase the size of all holes in the stencil by this amount (in mm). Use this if you find holes get printed smaller than they should.",
        initial=0.0,
        help_text="Use negative values to increase the space between tightly spaced pads at the cost of making the pads smaller.",
    )
    simplify_regions = forms.BooleanField(
        label="Replace regions (usually rounded rectangles) with bounding boxes. <br/> Use this if you find the processing takes extremely long, but note it might have unintended effects other than removing rounded corners.",
        initial=False,
        required=False,
    )
    flip_stencil = forms.BooleanField(
        label="Flip the stencil (use this for bottom layer stencils)",
        initial=False,
        required=False,
    )
    stencil_width = forms.FloatField(
        label="Force width of the stencil (in mm) when outline file is not specified.",
        initial=0.0,
        required=False,
    )
    stencil_height = forms.FloatField(
        label="Force height of the stencil (in mm) when outline file is not specified.",
        initial=0.0,
        required=False,
    )
    stencil_margin = forms.FloatField(
        label="Set this to create rectangular area with specified margin (in mm) to use it as outline if outline file is not specified.",
        initial=0.0,
        required=False,
    )

    include_frame = forms.BooleanField(
        label="Add a thicker frame around the stencil. Allows using the stencil in consistently-sized fixtures.",
        initial=False,
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "collapse-checkbox include-frame"}),
    )
    frame_width = forms.FloatField(
        label="Width of the stencil frame (in mm).",
        initial=155,
    )
    frame_height = forms.FloatField(
        label="Height of the stencil frame (in mm).",
        initial=155,
    )
    frame_thickness = forms.FloatField(
        label="Width of the stencil frame (in mm).",
        initial=1.2,
    )

src/gts_service/views.py
from __future__ import annotations

import logging
import os
import subprocess
from random import randint

import gerber
from django.conf import settings
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render

from gerber_to_scad import (
    process_gerber,
)
from gts_service.forms import UploadForm


def _get_version() -> str:
    with open("version") as f:
        return f.read()


def main(request: HttpRequest) -> HttpResponse:
    form = UploadForm(request.POST or None, files=request.FILES or None)
    version = _get_version()
    if form.is_valid():
        outline_file = form.cleaned_data["outline_file"]
        solderpaste_file = request.FILES["solderpaste_file"]
        outline = None

        if outline_file:
            try:
                outline = gerber.loads(outline_file.read().decode("utf-8"))
            except Exception as e:
                logging.exception(e)
                outline = None
                form.errors["outline_file"] = [
                    "Invalid format, is this a valid gerber file?"
                ]

        try:
            solder_paste = gerber.loads(solderpaste_file.read().decode("utf-8"))
        except Exception as e:
            logging.exception(e)
            solder_paste = None
            form.errors["solderpaste_file"] = [
                "Invalid format, is this a valid gerber file?"
            ]

        if not form.errors:
            output = process_gerber(
                outline_file=outline,
                solderpaste_file=solder_paste,
                stencil_thickness=form.cleaned_data["stencil_thickness"],
                include_ledge=form.cleaned_data["include_ledge"],
                ledge_thickness=form.cleaned_data["ledge_thickness"],
                gap=form.cleaned_data["gap"],
                include_frame=form.cleaned_data["include_frame"],
                frame_width=form.cleaned_data["frame_width"],
                frame_height=form.cleaned_data["frame_height"],
                frame_thickness=form.cleaned_data["frame_thickness"],
                increase_hole_size_by=form.cleaned_data["increase_hole_size_by"],
                simplify_regions=form.cleaned_data["simplify_regions"],
                flip_stencil=form.cleaned_data["flip_stencil"],
                stencil_width=form.cleaned_data["stencil_width"],
                stencil_height=form.cleaned_data["stencil_height"],
                stencil_margin=form.cleaned_data["stencil_margin"],
            )

            file_id = randint(1000000000, 9999999999)
            scad_filename = f"/tmp/gts-{file_id}.scad"
            stl_filename = f"/tmp/gts-{file_id}.stl"

            with open(scad_filename, "w") as scad_file:
                scad_file.write(output)

            p = subprocess.Popen(
                [
                    settings.OPENSCAD_BIN,
                    "-o",
                    stl_filename,
                    scad_filename,
                ]
            )
            p.wait()

            if p.returncode:
                form.errors["__all__"] = ["Failed to create an STL file from inputs"]
            else:
                with open(stl_filename) as stl_file:
                    stl_data = stl_file.read()
                os.remove(stl_filename)

            # Clean up temporary files
            os.remove(scad_filename)

        if form.errors:
            return render(request, "main.html", {"form": form, "version": version})

        response = HttpResponse(stl_data, content_type="application/zip")
        response["Content-Disposition"] = (
            "attachment; filename=%s" % stl_filename.rsplit("/")[-1]
        )
        return response

    return render(request, "main.html", {"form": form, "version": version})

src/gts_service/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>solder-stencil.me - The super simple gerber file to solder stencil stl converter.</title>

  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
    crossorigin="anonymous"
  >

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  {% block extra_head %}{% endblock extra_head %}
</head>

<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="#">solder-stencil.me</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <p class="navbar-text">Convert gerber files to 3d printable solder stencils.</p>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  {% block body %}{% endblock %}

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
    integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
    crossorigin="anonymous"></script>
</body>

</html>

src/gts_service/templates/main.html
{% extends "base.html" %} {% load bootstrap3 %} {% block extra_head %}
<script>
$( document ).ready(function() {
  $(".collapse-checkbox").change(function(){
    if (this.checked) {
      $(this).closest('.collapse-container').find('.collapse-content').addClass('expanded');
    } else {
      $(this).closest('.collapse-container').find('.collapse-content').removeClass('expanded');
    }
  });

  $(".manual-stencil-size").change(function(){
    if (this.checked) {
      $("#id_outline_file").attr('disabled', 'disabled');
    } else {
      $("#id_outline_file").removeAttr('disabled');
    }
  })

  $(".include-frame").change(function(){
    if (this.checked) {
      $(".include-ledge").attr('checked', false).trigger('change');
    }

  })

  $(".include-ledge").change(function(){
    if (this.checked) {
      $(".include-frame").attr('checked', false).trigger('change');
    }
  })

});
</script>
<style>
  label {
    font-weight: normal;
  }
  .warning {
    font-weight: bold;
    color: #aa2200;
  }
  .upload-form-group {
    border: 1px solid #aaa;
    padding: 10px;
    width: 50%;
  }
  .upload-form-group h4 {
    font-size:1em;
    margin:0;
    margin-bottom:10px;
  }
  .form-group:last-of-type {
    margin-bottom:0;
  }
  .collapse-content {
    display: none;
  }
  .collapse-content.expanded {
    display: inherit;
  }
  input[type="checkbox"] {
    margin-right: 5px;
  }
</style>
{% endblock extra_head %} {% block body %}
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Upload your gerber files (one for the paste layer and one for the outline), get an STL
        file.</h3>
    </div>
    <div class="panel-body">
      <p>If you use <strong>eagle</strong>, you can find a CAM script that will export the right layers <a
          href="https://raw.githubusercontent.com/kirberich/gerber_to_scad/master/export_for_gts.cam">here</a>.

      <p>If you use <strong>Fritzing</strong>, select File -> Export -> For Production -> Extended Gerber and select a
        directory for the resulting files. Upload the file named <em>your_project_contour.gm1</em> for the outline and
        <em>your_project_pasteMaskTop.gtp</em> for the paste layer.
      </p>

      <p class="warning">
        This site is untested, unfinished, unpolished and unlikely to work for anything serious. Good luck.
      </p>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">File Upload</h3>
    </div>
    <div class="panel-body">
      <p><strong>ℹ️ See bottom of the page for some usage hints.</strong></p>
      <hr/>
      <form action="" method="POST" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        {% bootstrap_form_errors form type='non_fields' %}

        <h4>Files</h4>
        {% bootstrap_field form.solderpaste_file  %}
        {% bootstrap_field form.outline_file  %}
        <div class='upload-form-group collapse-container'>
          <input type='checkbox' class='collapse-checkbox manual-stencil-size' id='manual-stencil'/><label for='manual-stencil'>Define stencil size manually instead of from outline file.</label>
          <div class="collapse-content">
          {% bootstrap_field form.stencil_width  %}
          {% bootstrap_field form.stencil_height  %}
          {% bootstrap_field form.stencil_margin  %}
          </div>
        </div>
        <hr/>

        <h4>Processing Options</h4>
        {% bootstrap_field form.simplify_regions  %}
        {% bootstrap_field form.flip_stencil  %}
        {% bootstrap_field form.stencil_thickness  %}
        {% bootstrap_field form.increase_hole_size_by  %}
        {% bootstrap_field form.gap  %}
        <hr/>

        <h4>Ledge</h4>
        <div class='collapse-container'>
          {% bootstrap_field form.include_ledge  %}
          <div class="collapse-content expanded">
            {% bootstrap_field form.ledge_thickness  %}
          </div>
        </div>
        <hr/>

        <h4>Frame</h4>
        <div class='collapse-container'>
          {% bootstrap_field form.include_frame  %}
          <div class="collapse-content">
            {% bootstrap_field form.frame_width  %}
            {% bootstrap_field form.frame_height  %}
            {% bootstrap_field form.frame_thickness  %}
          </div>
        </div>
        <hr/>

        {% buttons %}
        <button type="submit" class="btn btn-primary">Convert to STL</button>
        {% endbuttons %}
      </form>
    </div>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Hints</h3>
    </div>
    <div class="panel-body">
      <ul>
        <li>If you find the pads and holes don't align properly, try increasing the distance between board and ledge by
          a few tenths of a millimeter. If that's not it, your printer's calibration might be off.</li>
        <li>You can use negative values for hole size increase to increase the separation between closely spaced tabs,
          to allow printing a separating line. The downside is that this makes all pads smaller.</li>
        <li>Some boards can produce 2-dimensional walls if pads directly touch each other, which can throw of slicers.
          If this happens, increase the hole size very slightly (like 0.001mm) to make the holes overlap.</li>
        <li>The thicker the stencil and the smaller the solder pads, the more paste will stick to the stencil. If you're
          not getting enough paste on the pads, make the holes bigger or reduce the stencil thickness.</li>
        <li>If you've got a file that's not working right, send it to me at <a
            href="mailto:rob@kirberich.uk">rob@kirberich.uk</a> and I'll have a look to see what's up.</li>
      </ul>
    </div>
  </div>

  <br /><br />

  <p>Special thanks to <a href="https://twitter.com/kazade" target="_blank">kazade</a> for the brilliant idea of using
    <a href="http://www.openscad.org/" target="_blank">OpenSCAD</a> to make this work. This app uses <a
      href="https://github.com/curtacircuitos/pcb-tools" target="_blank">pcb-tools</a> to read Gerber files and <a
      href="https://github.com/SolidCode/SolidPython" target="_blank">SolidPython</a> to generate OpenSCAD code.
    OpenSCAD is used to generate the resulting STL files. The website is built using <a
      href="https://www.djangoproject.com/" target="_blank">Django</a>.
  </p>

  <p>You can find the code for the underlying converter at <a href="https://github.com/kirberich/gerber_to_scad"
      target="_blank">https://github.com/kirberich/gerber_to_scad</a>. The code for the web app can be found at <a
      href="https://github.com/kirberich/gerber_to_scad_service"
      target="_blank">https://github.com/kirberich/gerber_to_scad_service</a>.</p>

  <p>Version {{version}}</p>

</div>
{% endblock %}